language: csharp
mono: 4.6.2
dist: xenial
solution: HomeGenie_Linux/HomeGenie_Linux.sln
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt install doxygen
install:
  - nuget restore HomeGenie_Linux/HomeGenie_Linux.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
before_script: 
script:
- xbuild /p:Configuration=Debug HomeGenie_Linux/HomeGenie_Linux.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./HomeGenie.Tests/bin/Debug/HomeGenie.Tests.dll
after_success:
- HomeGenie_Linux/Packager/builddeb.sh
- sh doxygen.sh
after_failure: 
before_deploy:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
deploy:
  provider: releases
  deploy_key: github_deploy_key
  file_glob: true
  file:
    - HomeGenie_Linux/Packager/Output/*
    - Doxy/homegenie_api.tgz
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: genielabs/HomeGenie

